// <auto-generated />
using System;
using Dating_web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dating_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030090602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dating_web.Models.BaoCao", b =>
                {
                    b.Property<string>("BaoCaoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("bao_cao_id");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do");

                    b.Property<string>("NguoiBaoCaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_bao_cao_id");

                    b.Property<string>("NguoiBiBaoCaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_bi_bao_cao_id");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.HasKey("BaoCaoId");

                    b.HasIndex("NguoiBaoCaoId");

                    b.HasIndex("NguoiBiBaoCaoId");

                    b.ToTable("bao_cao");
                });

            modelBuilder.Entity("Dating_web.Models.HoSo", b =>
                {
                    b.Property<string>("HoSoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ho_so_id");

                    b.Property<string>("AlbumAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("album_anh");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_va_ten");

                    b.Property<string>("MoTaBanThan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta_ban_than");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<string>("SoThich")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_thich");

                    b.HasKey("HoSoId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ho_so");
                });

            modelBuilder.Entity("Dating_web.Models.MatchUser", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("match_id");

                    b.Property<string>("NguoiAId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_a_id");

                    b.Property<string>("NguoiBId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_b_id");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.HasKey("MatchId");

                    b.HasIndex("NguoiAId");

                    b.HasIndex("NguoiBId");

                    b.ToTable("match_user");
                });

            modelBuilder.Entity("Dating_web.Models.NguoiDung", b =>
                {
                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("NguoiDungId");

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("Dating_web.Models.TaiKhoanVip", b =>
                {
                    b.Property<string>("VipId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("vip_id");

                    b.Property<string>("GoiVip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("goi_vip");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_dung_id");

                    b.HasKey("VipId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("tai_khoan_vip");
                });

            modelBuilder.Entity("Dating_web.Models.Thich", b =>
                {
                    b.Property<string>("NguoiGuiId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_gui_id");

                    b.Property<string>("NguoiNhanId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_nhan_id");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.HasKey("NguoiGuiId", "NguoiNhanId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("thich");
                });

            modelBuilder.Entity("Dating_web.Models.TinNhan", b =>
                {
                    b.Property<string>("TinNhanId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tin_nhan_id");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("match_id");

                    b.Property<string>("NguoiGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nguoi_gui_id");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.HasKey("TinNhanId");

                    b.HasIndex("MatchId");

                    b.HasIndex("NguoiGuiId");

                    b.ToTable("tin_nhan");
                });

            modelBuilder.Entity("Dating_web.Models.BaoCao", b =>
                {
                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiBaoCao")
                        .WithMany()
                        .HasForeignKey("NguoiBaoCaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiBiBaoCao")
                        .WithMany()
                        .HasForeignKey("NguoiBiBaoCaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiBaoCao");

                    b.Navigation("NguoiBiBaoCao");
                });

            modelBuilder.Entity("Dating_web.Models.HoSo", b =>
                {
                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Dating_web.Models.MatchUser", b =>
                {
                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiA")
                        .WithMany()
                        .HasForeignKey("NguoiAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiB")
                        .WithMany()
                        .HasForeignKey("NguoiBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiA");

                    b.Navigation("NguoiB");
                });

            modelBuilder.Entity("Dating_web.Models.TaiKhoanVip", b =>
                {
                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Dating_web.Models.Thich", b =>
                {
                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("Dating_web.Models.TinNhan", b =>
                {
                    b.HasOne("Dating_web.Models.MatchUser", "MatchUser")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dating_web.Models.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchUser");

                    b.Navigation("NguoiGui");
                });
#pragma warning restore 612, 618
        }
    }
}
